# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sampo\Python\PycharmProjects\scinode\scinodes_poc\src\main\python\plugins\SignalsCombine\Ui_SignalsCombineSettingsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_SignalsCombineSettingsView(object):
    def setupUi(self, SignalsCombineSettingsView):
        SignalsCombineSettingsView.setObjectName("SignalsCombineSettingsView")
        SignalsCombineSettingsView.resize(415, 224)
        self.layoutWidget = QtWidgets.QWidget(SignalsCombineSettingsView)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 248, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)

        self.retranslateUi(SignalsCombineSettingsView)
        QtCore.QMetaObject.connectSlotsByName(SignalsCombineSettingsView)

    def retranslateUi(self, SignalsCombineSettingsView):
        _translate = QtCore.QCoreApplication.translate
        SignalsCombineSettingsView.setWindowTitle(_translate("SignalsCombineSettingsView", "Form"))
        self.label_8.setText(_translate("SignalsCombineSettingsView", "SignalsCombine settings"))
